Repository ontohub/indexer, pull requests merged in 2018-02, with the labels that each got.

#9 Fix production environment.
  bin/console
  bin/indexer
  lib/tasks/application.rake
Labels: ready for review

#10 Add the queue in the correct vhost
  app/workers/indexing_worker.rb
Labels: approved

#11 Simplify rubocop config.
  .rubocop.yml
  .rubocop_disabled.yml
  .rubocop_enabled.yml
  .rubocop_modified.yml
  app/indexers/organization_indexer.rb
  app/indexers/repository_indexer.rb
  app/indexers/user_indexer.rb
  app/jobs/indexing_job.rb
  app/workers/indexing_worker.rb
  config/initializers/chewy_sequel_table_name_fix.rb
  spec/indexers/organization_indexer_spec.rb
  spec/jobs/indexing_job_spec.rb
  spec/support/devise_mailer_stub.rb
  spec/support/tempdir.rb
Labels: in review
